using System.Collections;
using System.Collections.Generic;
using UnityEngine;

enum SpellEnum {
    SIMPLE_RECTANGLE,
    SIMPLE_TRIANGLE,
    SIMPLE_CIRCLE,
    DOUBLE_RECTANGLE,
    DOUBLE_TRIANGLE,
    DOUBLE_CIRCLE,
    RECTANGLE_TRIANGLE,
    RECTANGLE_CIRCLE,
    TRIANGLE_RECTANGLE,
    TRIANGLE_CIRCLE,
    CIRCLE_RECTANGLE,
    CIRCLE_TRIANGLE
}